### ISSUE TITLE
Clase Ventana de Estadisticas 

### ISSUE THREAD

**Issue by jochaes** [jochaes/FindRoute-Algoritmos-Geneticos#10]
Una clase que tenga todas las estadísticas y que se conecte al html y muestre la info 

Ventana que muestre las estadísticas de la generación actual, y de cada individuo 

Puede ser controlada desde la clase de juego

**Comment by jochaes** [comment]
### [Se puede ver algo así ](https://www.figma.com/file/eCXXkN0Qxd277fuELVgTwt/Prototipo-para-la-interfaz-gr%C3%A1fica?node-id=0%3A1)

**Comment by hros19** [comment]
Algo así había pensado, me gusta la idea de las estadísticas. Podrían meter por ahí el título del proyecto nada más con fin decorativo, lo demás lo veo muy bien.

**Comment by jochaes** [comment]
Ok perfe

**Comment by hros19** [comment]
Terminado
