### ISSUE TITLE
Animaciones y tema visual para el tablero 

### ISSUE THREAD

**Issue by jochaes** [jochaes/FindRoute-Algoritmos-Geneticos#13]
Animaciones y Gráficos (CSS) para los siguientes componentes del Tablero 
- [ ] Individuos
- [ ] También Animación para cuando se "Mueren"  los individuos 
- [ ] Obstáculos 
- [ ] Fondo 
- [ ] Punto Inicio 
- [ ] Punto final

**Comment by hros19** [comment]
Listo
