### ISSUE TITLE
Algoritmo Genético 2 - Idea por definir - (Habíamos dicho que premios, pero hay que ver cómo nos va)

### ISSUE THREAD

**Issue by jochaes** [jochaes/FindRoute-Algoritmos-Geneticos#3]
Algoritmo que se encargue de hacer algo más, por ejemplo que busque que la población se sienta atraída por premios, o que logre tener un poco de conciencia del ambiente y que los individuos logren evitar obstáculos más fácilmente, o puede ser cualquier otra cosa. 
I

**Comment by hros19** [comment]
Ya está implementado solo que no esperen mucho de los premios, el individuo se enfoca más en llegar en la menor distancia posible.
