### ISSUE TITLE
Clases para objetos que se deben pintar / en el archivo lógica 

### ISSUE THREAD

**Issue by jochaes** [jochaes/FindRoute-Algoritmos-Geneticos#7]
- [ ] Clase para crear el dibujo de los individuos 

- [ ] Clase para  crear el dibujo de los premios
- [ ] Clase para crear el dibujo del inicio y final 
- [ ] Clase para crear el dibujo de los obstáculos  

Estas clases reciben la posición en donde se van a dibujar, y el tamaño. 
algo así por ejemplo cuando se crea una bolita
var objet = {id:"circle_1", cx: Math.floor(s_w/2), cy: Math.floor(s_h/2), r: ball_r, stroke: "green", fill: "yellow" }

Dentro debe haber la función para crear el SVG ( ósea la función de drawCircle por ejemplo )

**En la clase de los individuos(bolita)**
Una idea es que en la función simularEtapa de la clase Entorno, mediante la clase Dibujar, se creen todas las bolitas con los movimientos, y los atributos de cada individuo. 
Luego en la clase Dibujar, exista una clase mover con un for que recorra la lista de individuos y haga mover(individuo) y que se mueva a la siguiente posición que esté en la lista de movimientos del individuo. 
O también la clase mover puede ser 
mover( bolita.sigMovimiento, bolita.id_bolita)

y la función mover, mueva la bolita con el id movimiento y el id que recibe

**Comment by hros19** [comment]
En mi opinión creo que no es necesario modificar el archivo lógica, no sé que tanto les lleve de código hacer lo de los movimientos pero podría ser en el mismo index, la clase de entorno regresa la población en cada etapa y se podrían gestionar los movimientos en el mismo index.js

**Comment by jochaes** [comment]
Claro, cuando lo pensé, creo que no lo había visto, pero sí, al final hicimos las clases que creemos necesarias y todo lo manejamos desde el index
